from arguments import Arguments
import os
import subprocess

def main():
    """This program will allow you to import a group of csv files. 

    This was written particularly for the data generated by my automated pong game. It will allow me to easily store this data 
    in a hdf5 file with attributes without doing much manual work. 
    """

    # Parse arguments
    argData = Arguments()
    hdf5PackerPath = "C:\Android_SDK\UM_Thesis_HDF5_Data_Packer\Source\__main__.py"

    # Walk through the input dirs to process them
    for root, dirs, files in os.walk(argData.data_input_dir):
        # Get decoded root path
        decodedPath = root.encode('utf-8', 'surrogateescape').decode('ISO-8859-1')
        for name in dirs:
            decodedName = name.encode('utf-8', 'surrogateescape').decode('ISO-8859-1')
            fullPath = os.path.join(decodedPath, decodedName)

            try:
                # Put together the command based on which directory we're on and user input
                command = "python {hdf5Packer} {dir_name} {hdf5_file} {dataset_group} {OS}".format(
                    hdf5Packer=hdf5PackerPath,
                    dir_name=fullPath,
                    hdf5_file=argData.hdf5_file,
                    dataset_group=argData.dataset_group,
                    OS=argData.os)
                subprocess.check_call(command, shell=True, stderr=subprocess.STDOUT)

            # Stop the program if something went wrong here
            except subprocess.CalledProcessError as ex:
                output = ex.output
                returncode = ex.returncode
                print("Problem processing directory {dir_name}. {msg}".format(dir_name=name, msg=output))
                raise
            except Exception as ex:
                print("Problem processing directory {dir_name}. {msg}".format(dir_name=name, msg=str(ex)))
                raise


if __name__ == "__main__":
    main()