from csvtohdf5 import CsvToHDF5
from arguments import Arguments
import os
import h5py

def main():
    """This program will allow you to import a group of csv files. 

    This was written particularly for the data generated by my automated pong game. It will allow me to easily store this data 
    in a hdf5 file with attributes without doing much manual work. 
    """

    # Parse arguments
    argData = Arguments()

    # Add the tables to the group(s)
    with h5py.File(argData.HDF5_output_file, 'a') as hdf5_file:

        # Create the converter
        csv_hdf5_converter = CsvToHDF5(hdf5_file, argData.len_diff_threshold)

        # Add the tables 
        for csv_file in argData.data_input_csvs:
            if 'metadata' not in csv_file:
                # If it's not a metadata csv, create the hdf5 file
                dataset_name = os.path.splitext(os.path.basename(csv_file))[0]
                full_dataset_name = '{base}/{new}'.format(base=argData.full_dataset_name, new=dataset_name)
                csv_hdf5_converter.add_dataset_from_csv(csv_file, full_dataset_name)
      
    # Add the metadata to the dataset or group
    # This needs to be done in another pass because of problems with improper file flushing/closing
    with h5py.File(argData.HDF5_output_file, 'a') as hdf5_file:

        # Create the converter
        csv_hdf5_converter = CsvToHDF5(hdf5_file, argData.len_diff_threshold)

        for csv_file in argData.data_input_csvs:
            if 'metadata' in csv_file:
                # If it is a metadata csv, add the metadata to the main dataset
                csv_hdf5_converter.add_metadata_from_csv(csv_file, argData.full_dataset_name_no_os)

if __name__ == "__main__":
    main()